import { serve } from "https://deno.land/std@0.208.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const ANON = Deno.env.get("SUPABASE_ANON_KEY")!;

interface RunSummary {
  total: number;
  passed: number;
  failed: number;
  verdict?: string;
  signature: string;
  raw?: any;
}

function summarize(raw: any): RunSummary {
  const results = raw?.results ?? raw?.tests ?? [];
  const total = raw?.summary?.total_tests ?? results.length ?? 0;
  const passed = raw?.summary?.passed ?? results.filter((r: any) => r.status === "pass" || r.status === "success").length ?? 0;
  const failed = raw?.summary?.failed ?? results.filter((r: any) => r.status === "fail" || r.status === "failed").length ?? 0;
  // Build deterministic signature from sorted step:status pairs
  const sig = results
    .map((r: any) => `${r.step ?? r.name ?? "?"}:${r.status ?? "?"}`)
    .sort()
    .join("|");
  return { total, passed, failed, verdict: raw?.summary?.overall_status, signature: sig, raw };
}

function renderReport(opts: {
  migration_version: string;
  triggered_by: string;
  run1: RunSummary;
  run2: RunSummary;
  deterministic: boolean;
  verdict: string;
  startedAt: string;
  durationMs: number;
}): string {
  const { migration_version, triggered_by, run1, run2, deterministic, verdict, startedAt, durationMs } = opts;
  return `# Post-Migration Regression Report

**Migration:** \`${migration_version}\`
**Triggered:** ${triggered_by}
**Started:** ${startedAt}
**Duration:** ${(durationMs / 1000).toFixed(1)}s
**Verdict:** **${verdict}**
**Deterministic:** ${deterministic ? "YES" : "NO"}

## Run 1
- Total: ${run1.total}
- Passed: ${run1.passed}
- Failed: ${run1.failed}
- Status: ${run1.verdict ?? "n/a"}

## Run 2
- Total: ${run2.total}
- Passed: ${run2.passed}
- Failed: ${run2.failed}
- Status: ${run2.verdict ?? "n/a"}

## Determinism Check
- Run 1 signature hash: \`${hash(run1.signature)}\`
- Run 2 signature hash: \`${hash(run2.signature)}\`
- Match: ${run1.signature === run2.signature ? "YES" : "NO"}

## Sign-off
- [ ] Engineering reviewed
- [ ] QA reviewed
- [ ] Release approved (if SHIPPABLE)

---
Generated by \`post-migration-regression\` edge function.
`;
}

function hash(s: string): string {
  let h = 0;
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) | 0;
  return (h >>> 0).toString(16);
}

async function authorize(req: Request): Promise<{ ok: boolean; user?: any }> {
  const auth = req.headers.get("Authorization") || "";
  const token = auth.replace("Bearer ", "").trim();
  if (!token) return { ok: false };
  if (token === SERVICE_ROLE) return { ok: true, user: { role: "service_role" } };
  // Validate admin JWT
  const sb = createClient(SUPABASE_URL, ANON, { global: { headers: { Authorization: auth } } });
  const { data, error } = await sb.auth.getUser(token);
  if (error || !data?.user) return { ok: false };
  const { data: isAdmin } = await sb.rpc("has_role", { _user_id: data.user.id, _role: "admin" });
  return { ok: !!isAdmin, user: data.user };
}

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  const authz = await authorize(req);
  if (!authz.ok) {
    return new Response(JSON.stringify({ error: "Unauthorized" }), { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } });
  }

  const admin = createClient(SUPABASE_URL, SERVICE_ROLE);
  let body: any = {};
  try { body = await req.json(); } catch { /* empty */ }
  const migration_version: string = body.migration_version ?? "manual";
  const triggered_by: string = body.triggered_by ?? "manual";

  const startedAt = new Date().toISOString();
  const t0 = Date.now();

  // Insert running row
  const { data: row, error: insErr } = await admin
    .from("regression_runs")
    .insert({ migration_version, triggered_by, status: "running" })
    .select("id")
    .single();

  if (insErr) {
    return new Response(JSON.stringify({ error: insErr.message }), { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } });
  }
  const runId = row.id;

  try {
    // Run E2E twice
    const invokeE2E = async () => {
      const res = await fetch(`${SUPABASE_URL}/functions/v1/run-e2e-validation`, {
        method: "POST",
        headers: { Authorization: `Bearer ${SERVICE_ROLE}`, "Content-Type": "application/json" },
        body: JSON.stringify({}),
      });
      const json = await res.json().catch(() => ({}));
      return json;
    };

    const raw1 = await invokeE2E();
    const run1 = summarize(raw1);
    const raw2 = await invokeE2E();
    const run2 = summarize(raw2);

    const deterministic = run1.signature === run2.signature;
    const allPass = run1.failed === 0 && run2.failed === 0 && run1.total > 0 && run2.total > 0;
    const verdict = allPass && deterministic ? "SHIPPABLE" : (run1.failed === 0 || run2.failed === 0) ? "DEGRADED" : "BLOCKED";
    const durationMs = Date.now() - t0;

    const report = renderReport({ migration_version, triggered_by, run1, run2, deterministic, verdict, startedAt, durationMs });
    const reportPath = `${migration_version}__${startedAt.replace(/[:.]/g, "-")}.md`;

    const { error: upErr } = await admin.storage.from("regression-reports").upload(reportPath, new Blob([report], { type: "text/markdown" }), {
      upsert: true,
      contentType: "text/markdown",
    });
    if (upErr) console.error("report upload failed", upErr);

    await admin.from("regression_runs").update({
      status: "complete",
      run1_summary: { total: run1.total, passed: run1.passed, failed: run1.failed, verdict: run1.verdict, signature_hash: hash(run1.signature) },
      run2_summary: { total: run2.total, passed: run2.passed, failed: run2.failed, verdict: run2.verdict, signature_hash: hash(run2.signature) },
      deterministic,
      verdict,
      report_path: upErr ? null : reportPath,
      duration_ms: durationMs,
    }).eq("id", runId);

    return new Response(JSON.stringify({ success: true, run_id: runId, verdict, deterministic, report_path: reportPath }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e: any) {
    await admin.from("regression_runs").update({
      status: "error",
      error: e?.message ?? String(e),
      duration_ms: Date.now() - t0,
    }).eq("id", runId);
    return new Response(JSON.stringify({ success: false, error: e?.message ?? String(e) }), { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } });
  }
});
