import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { 
  RefreshCw, 
  Plus, 
  Bot,
  Check, 
  X
} from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

interface AutoGeneratedSuggestion {
  id: string;
  question: string;
  answer: string;
  category: string;
  confidence: number;
  source_context: string;
}

export const SimpleFAQManager: React.FC = () => {
  const [suggestions, setSuggestions] = useState<AutoGeneratedSuggestion[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const { toast } = useToast();

  const generateSuggestions = async () => {
    setIsGenerating(true);
    try {
      // Simulate AI-based content analysis
      const mockSuggestions: AutoGeneratedSuggestion[] = [
        {
          id: '1',
          question: "How do I reset my verification preferences?",
          answer: "You can reset your verification preferences by going to your Profile page and clicking on 'Verification Preferences'. From there, you can update your SMS and email settings.",
          category: "Authentication",
          confidence: 0.85,
          source_context: "Recent user support tickets about verification settings"
        },
        {
          id: '2',
          question: "What happens if I fail the final exam?",
          answer: "If you don't pass the final exam, you can retake it after reviewing the course material. There's no limit to the number of attempts.",
          category: "Certification",
          confidence: 0.92,
          source_context: "Course completion analytics and user behavior patterns"
        },
        {
          id: '3',
          question: "Can dispensary managers track employee progress in real-time?",
          answer: "Yes, dispensary managers have access to a comprehensive dashboard that shows real-time progress tracking for all enrolled employees.",
          category: "Management",
          confidence: 0.78,
          source_context: "Feature usage analytics from dispensary portal"
        },
        {
          id: '4',
          question: "How does the smart authentication system work?",
          answer: "Our smart authentication system automatically detects your user role and preferred verification method. Admins get quick SMS PIN entry, while maintaining security for all users.",
          category: "Authentication",
          confidence: 0.90,
          source_context: "Recent platform enhancement for role-based authentication"
        }
      ];

      setSuggestions(mockSuggestions);
      
      toast({
        title: "Suggestions Generated",
        description: `Generated ${mockSuggestions.length} FAQ suggestions based on recent platform activity`,
      });
    } catch (error) {
      console.error('Error generating suggestions:', error);
      toast({
        title: "Error",
        description: "Failed to generate FAQ suggestions",
        variant: "destructive",
      });
    } finally {
      setIsGenerating(false);
    }
  };

  const approveSuggestion = async (suggestion: AutoGeneratedSuggestion) => {
    setSuggestions(prev => prev.filter(s => s.id !== suggestion.id));
    
    // Here you would normally save to a database
    // For now, we'll just update the local state
    
    toast({
      title: "FAQ Entry Approved",
      description: "The suggestion has been approved and would be added to the FAQ system",
    });
  };

  const rejectSuggestion = (suggestion: AutoGeneratedSuggestion) => {
    setSuggestions(prev => prev.filter(s => s.id !== suggestion.id));
    toast({
      title: "Suggestion Rejected",
      description: "The suggestion has been removed",
    });
  };

  return (
    <div className="space-y-6">
      {/* Header with Actions */}
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-2xl font-bold">FAQ Management</h2>
          <p className="text-muted-foreground">
            Generate and manage AI-powered FAQ suggestions
          </p>
        </div>
        <div className="flex space-x-2">
          <Button
            onClick={generateSuggestions}
            disabled={isGenerating}
            className="flex items-center space-x-2"
          >
            <RefreshCw className={`h-4 w-4 ${isGenerating ? 'animate-spin' : ''}`} />
            <span>Generate Suggestions</span>
          </Button>
          <Button variant="outline">
            <Plus className="h-4 w-4 mr-2" />
            Add Manual Entry
          </Button>
        </div>
      </div>

      {/* AI Suggestions */}
      {suggestions.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center space-x-2">
              <Bot className="h-5 w-5 text-blue-600" />
              <span>AI-Generated Suggestions</span>
              <Badge variant="secondary">{suggestions.length}</Badge>
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            {suggestions.map((suggestion) => (
              <div key={suggestion.id} className="border rounded-lg p-4 space-y-3">
                <div className="flex justify-between items-start">
                  <div className="flex-1 space-y-2">
                    <h4 className="font-medium">{suggestion.question}</h4>
                    <p className="text-sm text-muted-foreground">{suggestion.answer}</p>
                    <div className="flex items-center space-x-2">
                      <Badge variant="outline">{suggestion.category}</Badge>
                      <Badge 
                        variant={suggestion.confidence > 0.8 ? "default" : "secondary"}
                        className="text-xs"
                      >
                        {Math.round(suggestion.confidence * 100)}% confidence
                      </Badge>
                    </div>
                    <p className="text-xs text-muted-foreground">
                      Source: {suggestion.source_context}
                    </p>
                  </div>
                  <div className="flex space-x-2 ml-4">
                    <Button
                      size="sm"
                      onClick={() => approveSuggestion(suggestion)}
                      className="bg-green-600 hover:bg-green-700"
                    >
                      <Check className="h-4 w-4" />
                    </Button>
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => rejectSuggestion(suggestion)}
                    >
                      <X className="h-4 w-4" />
                    </Button>
                  </div>
                </div>
              </div>
            ))}
          </CardContent>
        </Card>
      )}

      {suggestions.length === 0 && !isGenerating && (
        <Card>
          <CardContent className="text-center py-8">
            <Bot className="h-12 w-12 mx-auto text-muted-foreground mb-4" />
            <h3 className="text-lg font-medium mb-2">No suggestions yet</h3>
            <p className="text-muted-foreground mb-4">
              Click "Generate Suggestions" to create AI-powered FAQ entries based on platform usage
            </p>
            <Button onClick={generateSuggestions} disabled={isGenerating}>
              <RefreshCw className="h-4 w-4 mr-2" />
              Generate Suggestions
            </Button>
          </CardContent>
        </Card>
      )}
    </div>
  );
};