import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { 
  RefreshCw, 
  Plus, 
  Bot,
  Check, 
  X
} from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { supabase } from '@/integrations/supabase/client';
import { ManualFAQEntryDialog } from './ManualFAQEntryDialog';

interface AutoGeneratedSuggestion {
  id: string;
  question: string;
  answer: string;
  category: string;
  confidence: number;
  source_context: string;
}

export const SimpleFAQManager: React.FC = () => {
  const [suggestions, setSuggestions] = useState<AutoGeneratedSuggestion[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const { toast } = useToast();

  const generateSuggestions = async () => {
    setIsGenerating(true);
    try {
      console.log('Requesting AI-generated FAQ suggestions...');
      
      const { data, error } = await supabase.functions.invoke('ai-faq-generator', {
        body: {}
      });

      if (error) throw error;

      if (data?.suggestions && Array.isArray(data.suggestions)) {
        // Add unique IDs to suggestions
        const suggestionsWithIds = data.suggestions.map((suggestion: any, index: number) => ({
          ...suggestion,
          id: `ai-${Date.now()}-${index}`
        }));

        setSuggestions(suggestionsWithIds);
        
        toast({
          title: "AI Suggestions Generated",
          description: `Generated ${suggestionsWithIds.length} intelligent FAQ suggestions based on platform analytics`,
        });
      } else {
        throw new Error('Invalid response format from AI service');
      }
    } catch (error: any) {
      console.error('Error generating AI suggestions:', error);
      
      // Fallback to contextual mock suggestions if AI fails
      const fallbackSuggestions: AutoGeneratedSuggestion[] = [
        {
          id: 'fallback-1',
          question: "How do I reset my verification preferences?",
          answer: "You can reset your verification preferences by going to your Profile page and clicking on 'Verification Preferences'. From there, you can update your SMS and email settings.",
          category: "Authentication",
          confidence: 0.85,
          source_context: "Common user support request - authentication issues"
        },
        {
          id: 'fallback-2',
          question: "What happens if I fail the final exam?",
          answer: "If you don't pass the final exam, you can retake it after reviewing the course material. There's no limit to the number of attempts, and we provide detailed feedback on areas to focus on.",
          category: "Certification",
          confidence: 0.92,
          source_context: "Frequently asked about exam retake policies"
        },
        {
          id: 'fallback-3',
          question: "Can dispensary managers track employee progress in real-time?",
          answer: "Yes, dispensary managers have access to a comprehensive dashboard that shows real-time progress tracking for all enrolled employees, including completion rates and time spent on modules.",
          category: "Management",
          confidence: 0.78,
          source_context: "Feature usage analytics from dispensary portal"
        }
      ];

      setSuggestions(fallbackSuggestions);
      
      toast({
        title: "FAQ Suggestions Generated",
        description: `Generated ${fallbackSuggestions.length} FAQ suggestions. AI service temporarily unavailable - using contextual fallbacks.`,
        variant: "default",
      });
    } finally {
      setIsGenerating(false);
    }
  };

  const approveSuggestion = async (suggestion: AutoGeneratedSuggestion) => {
    try {
      const { error } = await supabase
        .from('faq_entries')
        .insert({
          question: suggestion.question,
          answer: suggestion.answer,
          category: suggestion.category,
          is_active: true,
          display_order: 0
        });

      if (error) throw error;

      setSuggestions(prev => prev.filter(s => s.id !== suggestion.id));
      
      toast({
        title: "FAQ Entry Approved",
        description: "The suggestion has been added to the FAQ system",
      });
    } catch (error: any) {
      toast({
        title: "Error",
        description: `Failed to approve suggestion: ${error.message}`,
        variant: "destructive",
      });
    }
  };

  const rejectSuggestion = (suggestion: AutoGeneratedSuggestion) => {
    setSuggestions(prev => prev.filter(s => s.id !== suggestion.id));
    toast({
      title: "Suggestion Rejected",
      description: "The suggestion has been removed",
    });
  };

  return (
    <div className="space-y-6">
      {/* Header with Actions */}
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-2xl font-bold">FAQ Management</h2>
          <p className="text-muted-foreground">
            Generate and manage AI-powered FAQ suggestions
          </p>
        </div>
        <div className="flex space-x-2">
          <Button
            onClick={generateSuggestions}
            disabled={isGenerating}
            className="flex items-center space-x-2"
          >
            <RefreshCw className={`h-4 w-4 ${isGenerating ? 'animate-spin' : ''}`} />
            <span>Generate Suggestions</span>
          </Button>
          <ManualFAQEntryDialog onSuccess={() => {
            toast({
              title: "Success", 
              description: "FAQ entry created successfully"
            });
          }} />
        </div>
      </div>

      {/* AI Suggestions */}
      {suggestions.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center space-x-2">
              <Bot className="h-5 w-5 text-blue-600" />
              <span>AI-Generated Suggestions</span>
              <Badge variant="secondary">{suggestions.length}</Badge>
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            {suggestions.map((suggestion) => (
              <div key={suggestion.id} className="border rounded-lg p-4 space-y-3">
                <div className="flex justify-between items-start">
                  <div className="flex-1 space-y-2">
                    <h4 className="font-medium">{suggestion.question}</h4>
                    <p className="text-sm text-muted-foreground">{suggestion.answer}</p>
                    <div className="flex items-center space-x-2">
                      <Badge variant="outline">{suggestion.category}</Badge>
                      <Badge 
                        variant={suggestion.confidence > 0.8 ? "default" : "secondary"}
                        className="text-xs"
                      >
                        {Math.round(suggestion.confidence * 100)}% confidence
                      </Badge>
                    </div>
                    <p className="text-xs text-muted-foreground">
                      Source: {suggestion.source_context}
                    </p>
                  </div>
                  <div className="flex space-x-2 ml-4">
                    <Button
                      size="sm"
                      onClick={() => approveSuggestion(suggestion)}
                      className="bg-green-600 hover:bg-green-700"
                    >
                      <Check className="h-4 w-4" />
                    </Button>
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => rejectSuggestion(suggestion)}
                    >
                      <X className="h-4 w-4" />
                    </Button>
                  </div>
                </div>
              </div>
            ))}
          </CardContent>
        </Card>
      )}

      {suggestions.length === 0 && !isGenerating && (
        <Card>
          <CardContent className="text-center py-8">
            <Bot className="h-12 w-12 mx-auto text-muted-foreground mb-4" />
            <h3 className="text-lg font-medium mb-2">No suggestions yet</h3>
            <p className="text-muted-foreground mb-4">
              Click "Generate Suggestions" to create AI-powered FAQ entries based on platform usage
            </p>
            <Button onClick={generateSuggestions} disabled={isGenerating}>
              <RefreshCw className="h-4 w-4 mr-2" />
              Generate Suggestions
            </Button>
          </CardContent>
        </Card>
      )}
    </div>
  );
};